Brush up rngd_nistbeacon.c
1) Fix a possile NULL dereference in get_nist_record() and update_active_cert().
It may happen in an unlikely case when curl_easy_setopt(CURLOPT_WRITEFUNCTION)
fails but curl_easy_perform() succeeds.

Also adjust error handling and logging. This way a libcurl instance is properly
cleaned up in all cases.

This fixes code for the following warnings. NULL pointer warning still stays,
as covscan does not recognize parse_nist_json_block() as a callback.

Error: CHECKED_RETURN (CWE-252): [#def13]
rng-tools-6.12/rngd_nistbeacon.c:582: check_return: Calling "curl_easy_setopt(curl,
_curl_opt, certurl)" without checking return value. This library function may fail
and return an error code.
   581|   certurl = strcat(certurl, block.certificateIdString);
   582|-> curl_easy_setopt(curl, CURLOPT_URL, certurl);

Error: CLANG_WARNING: [#def19]
rng-tools-6.12/rngd_nistbeacon.c:622:32: warning[core.NonNullParamChecker]: Null
pointer passed to 1st parameter expecting 'nonnull'
   622|-> activeCertId = strndup(block.certificateId, be32toh(block.certificateIdLen));

2) Remove unused variables from parse_nist_json_block().

3) Fix a signedness warning for nist_rand_buf and block.signatureValue.

Signed-off-by: Vladis Dronov <vdronov@redhat.com>