rngd_jitter: disambiguate call to encrypt
Commit 0f184ea7e792427fb20afe81d471b565aee96f0b disambiguate the call to
encrypt in rngd_rdrand.c but did not update rngd_jitter.c.

This raise the following build failure:

rngd_jitter.c:75:12: error: conflicting types for 'encrypt'
 static int encrypt(unsigned char *plaintext, int plaintext_len, unsigned char *key,
            ^~~~~~~
In file included from rngd_jitter.c:27:
/home/dawncrow/buildroot-test/scripts/instance-0/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/include/unistd.h:1132:13: note: previous declaration of 'encrypt' was here
 extern void encrypt (char *__block, int __edflag) __THROW __nonnull ((1));
             ^~~~~~~
Makefile:770: recipe for target 'rngd-rngd_jitter.o' failed

Fixes:
 - http://autobuild.buildroot.org/results/0ca6bf16e3acbc94065b88c4442d6595424b77cb

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>